# Generated by Django 5.1.7 on 2025-08-09 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech_analysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpromptuTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=500)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('difficulty_level', models.CharField(default='medium', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='audiorecording',
            name='topic',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='audiorecording',
            name='virtual_scene',
            field=models.CharField(default='small-audience', max_length=100),
        ),
        migrations.AddField(
            model_name='speakingtask',
            name='instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='speakingtask',
            name='time_limit',
            field=models.IntegerField(default=3),
        ),
    ]
